language: cpp
sudo: false

compiler: clang

matrix:
    include:
        - os: linux
          dist: focal
          compiler: gcc
          env:
              - CONF=release
        - os: linux
          dist: focal
          compiler: gcc
          env:
              - CONF=debug
              - GCOV_FLAGS='--coverage'
          after_success:
              - pip install --user cpp-coveralls
              - $CXX --version
              - /usr/bin/gcov-9 --v
              - coveralls -h
              - coveralls -r .. --gcov /usr/bin/gcov-9 --gcov-options '\-lp' -i src/core
        - os: linux
          dist: focal
          compiler: clang
          env:
              - CONF=release
        - os: linux
          dist: focal
          compiler: clang
          env:
              - CONF=debug


# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

# use a more modern gcc, 8 should also work (in theory) but not 7.4 (missing filesystem)
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi


addons:
  apt:
    update: true
    packages:
      - libsdl2-dev
      - libassimp-dev
      - lcov

script:
  - $CXX --version
  - python3 --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake -DCMAKE_BUILD_TYPE=$CONF -DEXTRA_FLAGS="$GCOV_FLAGS" ..
  - cmake --build .
  - ./libs/tests/tests_test
  - ./libs/core/core_test
  - ./libs/minsynth/minsynth_test
  - ./libs/duk/duk_test

# temporarily disabled
#  - cd ..
#  - ./scripts/clang.py tidy

