dist: bionic
sudo: false
language: cpp

# gcc might not work
compiler:
  - clang
  - gcc

# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

# use a more modern gcc, 8 should also work (in theory) but not 7.4 (missing filesystem)
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-8" CC="gcc-8"; fi


addons:
  apt:
    update: true
    packages:
      - libsdl2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libassimp-dev
      - libwxgtk3.0-dev
      - gcc-8
      - g++-8

script:
  - $CXX --version
  - python3 --version
  - mkdir build
  - cd build
  - cmake ..
  - make VERBOSE=1
  - ./unit-tests/tests
