dist: trusty
sudo: false
language: cpp

# Handle git submodules yourself
git:
    submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
      - deadsnakes
    packages:
      - g++-5
      - libsdl2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libassimp-dev
      - libwxgtk3.0-dev
      - python3.5

# https://github.com/travis-ci/travis-ci/issues/3668#issuecomment-279276549
install:
   - mkdir -p latest-symlinks
   - ln -s /usr/bin/python3.7 latest-symlinks/python3
   - export PATH=$PWD/latest-symlinks:$PATH

script:
  - $CXX --version
  - python3 --version
  - mkdir build
  - cd build
  - CXX=/usr/bin/g++-5 CC=/usr/bin/gcc-5 cmake ..
  - make VERBOSE=1
  - cd tests
  - ./tests
