language: cpp
sudo: false

compiler: clang

matrix:
    include:
        - os: linux
          dist: bionic
          env:
              - CONF=release
        - os: linux
          dist: bionic
          env:
              - CONF=debug
              - GCOV_FLAGS='--coverage'
          after_success:
              - pip install --user cpp-coveralls
              - coveralls -h
              - coveralls -r .. --gcov-options '\-lp' -i core


# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive

# use a more modern gcc, 8 should also work (in theory) but not 7.4 (missing filesystem)
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi


# sources for gcc/++-9
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libsdl2-dev
      - libprotobuf-dev
      - protobuf-compiler
      - libassimp-dev
      - libwxgtk3.0-dev
      - gcc-9
      - g++-9

script:
  - $CXX --version
  - python3 --version
  - mkdir build
  - cd build
  - cmake ..
  - cmake -DCMAKE_BUILD_TYPE=$CONF -DEXTRA_FLAGS="$GCOV_FLAGS" ..
  - cmake --build .
  - ./tests/tests
  - ./tests/tests
  - cd ..
  - ./scripts/clang.py tidy
