environment:
  matrix:
  # 2015 seems to be too old for euphoria
  #  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  #    EUPH_COMPILER: vs2015
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      EUPH_COMPILER: vs2019
  # Python 3.4 has outdated pip
  # https://github.com/jakubroztocil/httpie/blob/master/appveyor.yml
  PYTHON: 'C:\Python36'

clone_folder: c:\projects\euphoria

install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule update --init --recursive
  - cmd: 'echo %PYTHON%'
  - cmd: 'echo %EUPH_COMPILER%'
  - cmd: '%PYTHON%/python.exe -m pip install requests'
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py install %EUPH_COMPILER% auto'

before_build:
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py cmake %EUPH_COMPILER% auto'

build_script:
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py build %EUPH_COMPILER% auto'

# - build\deps -> appveyor.yml, scripts\**.py
cache:
  - build\deps

test_script:
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py test'
  - ps: c:\projects\euphoria\scripts\upload-test-appveyor.ps1
