image:
  - Visual Studio 2017

clone_folder: c:\projects\euphoria

install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule update --init --recursive
  - cmd: pip3 install requests
  - cmd: 'c:\projects\euphoria\scripts\windows.py install'

before_build:
  - cmd: 'c:\projects\euphoria\scripts\windows.py cmake'

build_script:
  - cmd: 'c:\projects\euphoria\scripts\windows.py build'

cache:
  - build\deps

test_script:
  - c:\projects\euphoria\scripts\windows.py test
