image:
  - Visual Studio 2017

clone_folder: c:\projects\euphoria

# Python 3.4 has outdated pip
# https://github.com/jakubroztocil/httpie/blob/master/appveyor.yml
environment:
  PYTHON: "C:\Python36"

install:
  - cmd: sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - cmd: git submodule update --init --recursive
  - cmd: '%PYTHON%\Scripts\pip.exe install requests'
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py install'

before_build:
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py cmake'

build_script:
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py build'

cache:
  - build\deps

test_script:
  - cmd: '%PYTHON%\python.exe c:\projects\euphoria\scripts\windows.py test'
