image:
  - Visual Studio 2017

clone_folder: c:\projects\euphoria

install:
  - cmd: git submodule update --init --recursive
  - cmd: 'c:\projects\euphoria\scripts\windows.py install'

before_build:
  - cmd: 'c:\projects\euphoria\scripts\windows.py cmake'

build_script:
  - cmd: 'c:\projects\euphoria\scripts\windows.py build'
