{
    "ignore":
    [
        "apps/",
        "external/",
        "libs/assert/",
        "libs/core/examples/",
        "libs/core/test/main.cc"
        "libs/file_types/",
        "libs/gui/",
        "libs/log/",
        "libs/render/",
        "libs/window/",
    ]
}
