#ifndef CORE_NAMED_COLORS_H
#define CORE_NAMED_COLORS_H

#include "core/enumtostring.h"

// https://blog.xkcd.com/2010/05/03/color-survey-results/
// https://xkcd.com/color/rgb/
// https://xkcd.com/color/rgb.txt
// 
// License: http://creativecommons.org/publicdomain/zero/1.0/
// 
// Changes:
//  - Grey related named changed to Gray
//  - 'lightgreen' and 'light green' have been merged into 'LightGreen' using the
//    'light green' color value as it looked nicer
// 
//
// todo: add custom colors, shader blue?
// 
enum class Color
{
  CloudyBlue ,
  DarkPastelGreen ,
  Dust ,
  ElectricLime ,
  FreshGreen ,
  LightEggplant ,
  NastyGreen ,
  ReallyLightBlue ,
  Tea ,
  WarmPurple ,
  YellowishTan ,
  Cement ,
  DarkGrassGreen ,
  DustyTeal ,
  GrayTeal ,
  MacaroniAndCheese ,
  PinkishTan ,
  Spruce ,
  StrongBlue ,
  ToxicGreen ,
  WindowsBlue ,
  BlueBlue ,
  BlueWithAHintOfPurple ,
  Booger ,
  BrightSeaGreen ,
  DarkGreenBlue ,
  DeepTurquoise ,
  GreenTeal ,
  StrongPink ,
  Bland ,
  DeepAqua ,
  LavenderPink ,
  LightMossGreen ,
  LightSeafoamGreen ,
  OliveYellow ,
  PigPink ,
  DeepLilac ,
  Desert ,
  DustyLavender ,
  PurpleyGray ,
  Purply ,
  CandyPink ,
  LightPastelGreen ,
  BoringGreen ,
  KiwiGreen ,
  LightGrayGreen ,
  OrangePink ,
  TeaGreen ,
  VeryLightBrown ,
  EggShell ,
  EggplantPurple ,
  PowderPink ,
  ReddishGray ,
  BabyShitBrown ,
  Liliac ,
  StormyBlue ,
  UglyBrown ,
  Custard ,
  DarkishPink ,
  DeepBrown ,
  GreenishBeige ,
  Manilla ,
  OffBlue ,
  BattleshipGray ,
  BrownyGreen ,
  Bruise ,
  KelleyGreen ,
  SicklyYellow ,
  SunnyYellow ,
  Azul ,
  Darkgreen ,
  GreenOrYellow ,
  Lichen ,
  LightLightGreen ,
  PaleGold ,
  SunYellow ,
  TanGreen ,
  Burple ,
  Butterscotch ,
  Toupe ,
  DarkCream ,
  IndianRed ,
  LightLavendar ,
  PoisonGreen ,
  BabyPukeGreen ,
  BrightYellowGreen ,
  CharcoalGray ,
  Squash ,
  Cinnamon ,
  LightPeaGreen ,
  RadioactiveGreen ,
  RawSienna ,
  BabyPurple ,
  Cocoa ,
  LightRoyalBlue ,
  Orangeish ,
  RustBrown ,
  SandBrown ,
  Swamp ,
  TealishGreen ,
  BurntSiena ,
  Camo ,
  DuskBlue ,
  Fern ,
  OldRose ,
  PaleLightGreen ,
  PeachyPink ,
  RosyPink ,
  LightBluishGreen ,
  LightBrightGreen ,
  LightNeonGreen ,
  LightSeafoam ,
  TiffanyBlue ,
  WashedOutGreen ,
  BrownyOrange ,
  NiceBlue ,
  Sapphire ,
  GrayishTeal ,
  OrangeyYellow ,
  Parchment ,
  Straw ,
  VeryDarkBrown ,
  Terracota ,
  UglyBlue ,
  ClearBlue ,
  Creme ,
  FoamGreen ,
  GrayOrGreen ,
  LightGold ,
  SeafoamBlue ,
  Topaz ,
  VioletPink ,
  Wintergreen ,
  YellowTan ,
  DarkFuchsia ,
  IndigoBlue ,
  LightYellowishGreen ,
  PaleMagenta ,
  RichPurple ,
  SunflowerYellow ,
  GreenOrBlue ,
  Leather ,
  RacingGreen ,
  VividPurple ,
  DarkRoyalBlue ,
  Hazel ,
  MutedPink ,
  BoogerGreen ,
  Canary ,
  CoolGray ,
  DarkTaupe ,
  DarkishPurple ,
  TrueGreen ,
  CoralPink ,
  DarkSage ,
  DarkSlateBlue ,
  FlatBlue ,
  Mushroom ,
  RichBlue ,
  DirtyPurple ,
  Greenblue ,
  IckyGreen ,
  LightKhaki ,
  WarmBlue ,
  DarkHotPink ,
  DeepSeaBlue ,
  Carmine ,
  DarkYellowGreen ,
  PalePeach ,
  PlumPurple ,
  GoldenRod ,
  NeonRed ,
  OldPink ,
  VeryPaleBlue ,
  BloodOrange ,
  Grapefruit ,
  SandYellow ,
  ClayBrown ,
  DarkBlueGray ,
  FlatGreen ,
  LightGreenBlue ,
  WarmPink ,
  DodgerBlue ,
  GrossGreen ,
  Ice ,
  MetallicBlue ,
  PaleSalmon ,
  SapGreen ,
  Algae ,
  BlueyGray ,
  GreenyGray ,
  HighlighterGreen ,
  LightLightBlue ,
  LightMint ,
  RawUmber ,
  VividBlue ,
  DeepLavender ,
  DullTeal ,
  LightGreenishBlue ,
  MudGreen ,
  Pinky ,
  RedWine ,
  ShitGreen ,
  TanBrown ,
  Darkblue ,
  Rosa ,
  Lipstick ,
  PaleMauve ,
  Claret ,
  Dandelion ,
  Orangered ,
  PoopGreen ,
  Ruby ,
  Dark ,
  GreenishTurquoise ,
  PastelRed ,
  PissYellow ,
  BrightCyan ,
  DarkCoral ,
  AlgaeGreen ,
  DarkishRed ,
  ReddyBrown ,
  BlushPink ,
  CamouflageGreen ,
  LawnGreen ,
  Putty ,
  VibrantBlue ,
  DarkSand ,
  PurpleOrBlue ,
  Saffron ,
  Twilight ,
  WarmBrown ,
  Bluegray ,
  BubbleGumPink ,
  DuckEggBlue ,
  GreenishCyan ,
  Petrol ,
  Royal ,
  Butter ,
  DustyOrange ,
  OffYellow ,
  PaleOliveGreen ,
  Orangish ,
  Leaf ,
  LightBlueGray ,
  DriedBlood ,
  LightishPurple ,
  RustyRed ,
  LavenderBlue ,
  LightGrassGreen ,
  LightMintGreen ,
  Sunflower ,
  Velvet ,
  BrickOrange ,
  LightishRed ,
  PureBlue ,
  TwilightBlue ,
  VioletRed ,
  YellowyBrown ,
  Carnation ,
  MuddyYellow ,
  DarkSeafoamGreen ,
  DeepRose ,
  DustyRed ,
  GrayOrBlue ,
  LemonLime ,
  PurpleOrPink ,
  BrownYellow ,
  PurpleBrown ,
  Wisteria ,
  BananaYellow ,
  LipstickRed ,
  WaterBlue ,
  BrownGray ,
  VibrantPurple ,
  BabyGreen ,
  BarfGreen ,
  EggshellBlue ,
  SandyYellow ,
  CoolGreen ,
  Pale ,
  BlueOrGray ,
  HotMagenta ,
  Grayblue ,
  Purpley ,
  BabyShitGreen ,
  BrownishPink ,
  DarkAquamarine ,
  Diarrhea ,
  LightMustard ,
  PaleSkyBlue ,
  TurtleGreen ,
  BrightOlive ,
  DarkGrayBlue ,
  GreenyBrown ,
  LemonGreen ,
  LightPeriwinkle ,
  SeaweedGreen ,
  SunshineYellow ,
  UglyPurple ,
  MediumPink ,
  PukeBrown ,
  VeryLightPink ,
  Viridian ,
  Bile ,
  FadedYellow ,
  VeryPaleGreen ,
  VibrantGreen ,
  BrightLime ,
  Spearmint ,
  LightAquamarine ,
  LightSage ,
  Yellowgreen ,
  BabyPoo ,
  DarkSeafoam ,
  DeepTeal ,
  Heather ,
  RustOrange ,
  DirtyBlue ,
  FernGreen ,
  BrightLilac ,
  WeirdGreen ,
  PeacockBlue ,
  AvocadoGreen ,
  FadedOrange ,
  GrapePurple ,
  HotGreen ,
  LimeYellow ,
  Mango ,
  Shamrock ,
  Bubblegum ,
  PurplishBrown ,
  VomitYellow ,
  PaleCyan ,
  KeyLime ,
  TomatoRed ,
  Lightgreen ,
  Merlot ,
  NightBlue ,
  PurpleishPink ,
  Apple ,
  BabyPoopGreen ,
  GreenApple ,
  Heliotrope ,
  YellowOrGreen ,
  AlmostBlack ,
  CoolBlue ,
  LeafyGreen ,
  MustardBrown ,
  Dusk ,
  DullBrown ,
  FrogGreen ,
  VividGreen ,
  BrightLightGreen ,
  FluroGreen ,
  Kiwi ,
  Seaweed ,
  NavyGreen ,
  UltramarineBlue ,
  Iris ,
  PastelOrange ,
  YellowishOrange ,
  Perrywinkle ,
  Tealish ,
  DarkPlum ,
  Pear ,
  PinkishOrange ,
  MidnightPurple ,
  LightUrple ,
  DarkMint ,
  GreenishTan ,
  LightBurgundy ,
  TurquoiseBlue ,
  UglyPink ,
  Sandy ,
  ElectricPink ,
  MutedPurple ,
  MidGreen ,
  Grayish ,
  NeonYellow ,
  Banana ,
  CarnationPink ,
  Tomato ,
  Sea ,
  MuddyBrown ,
  TurquoiseGreen ,
  Buff ,
  Fawn ,
  MutedBlue ,
  PaleRose ,
  DarkMintGreen ,
  Amethyst ,
  BlueOrGreen ,
  Chestnut ,
  SickGreen ,
  Pea ,
  RustyOrange ,
  Stone ,
  RoseRed ,
  PaleAqua ,
  DeepOrange ,
  Earth ,
  MossyGreen ,
  GrassyGreen ,
  PaleLimeGreen ,
  LightGrayBlue ,
  PaleGray ,
  Asparagus ,
  Blueberry ,
  PurpleRed ,
  PaleLime ,
  GreenishTeal ,
  Caramel ,
  DeepMagenta ,
  LightPeach ,
  MilkChocolate ,
  Ocher ,
  OffGreen ,
  PurplyPink ,
  Lightblue ,
  DuskyBlue ,
  Golden ,
  LightBeige ,
  ButterYellow ,
  DuskyPurple ,
  FrenchBlue ,
  UglyYellow ,
  GreenyYellow ,
  OrangishRed ,
  ShamrockGreen ,
  OrangishBrown ,
  TreeGreen ,
  DeepViolet ,
  Gunmetal ,
  BlueOrPurple ,
  Cherry ,
  SandyBrown ,
  WarmGray ,
  DarkIndigo ,
  Midnight ,
  BlueyGreen ,
  GrayPink ,
  SoftPurple ,
  Blood ,
  BrownRed ,
  MediumGray ,
  Berry ,
  Poo ,
  PurpleyPink ,
  LightSalmon ,
  Snot ,
  EasterPurple ,
  LightYellowGreen ,
  DarkNavyBlue ,
  Drab ,
  LightRose ,
  Rouge ,
  PurplishRed ,
  SlimeGreen ,
  BabyPoop ,
  IrishGreen ,
  PinkOrPurple ,
  DarkNavy ,
  GreenyBlue ,
  LightPlum ,
  PinkishGray ,
  DirtyOrange ,
  RustRed ,
  PaleLilac ,
  OrangeyRed ,
  PrimaryBlue ,
  KermitGreen ,
  BrownishPurple ,
  MurkyGreen ,
  Wheat ,
  VeryDarkPurple ,
  BottleGreen ,
  Watermelon ,
  DeepSkyBlue ,
  FireEngineRed ,
  YellowOchre ,
  PumpkinOrange ,
  PaleOlive ,
  LightLilac ,
  LightishGreen ,
  CarolinaBlue ,
  Mulberry ,
  ShockingPink ,
  Auburn ,
  BrightLimeGreen ,
  Celadon ,
  PinkishBrown ,
  PooBrown ,
  BrightSkyBlue ,
  Celery ,
  DirtBrown ,
  Strawberry ,
  DarkLime ,
  Copper ,
  MediumBrown ,
  MutedGreen ,
  RobinSEgg ,
  BrightAqua ,
  BrightLavender ,
  Ivory ,
  VeryLightPurple ,
  LightNavy ,
  PinkRed ,
  OliveBrown ,
  PoopBrown ,
  MustardGreen ,
  OceanGreen ,
  VeryDarkBlue ,
  DustyGreen ,
  LightNavyBlue ,
  MintyGreen ,
  Adobe ,
  Barney ,
  JadeGreen ,
  BrightLightBlue ,
  LightLime ,
  DarkKhaki ,
  OrangeYellow ,
  Ocre ,
  Maize ,
  FadedPink ,
  BritishRacingGreen ,
  Sandstone ,
  MudBrown ,
  LightSeaGreen ,
  RobinEggBlue ,
  AquaMarine ,
  DarkSeaGreen ,
  SoftPink ,
  OrangeyBrown ,
  CherryRed ,
  BurntYellow ,
  BrownishGray ,
  Camel ,
  PurplishGray ,
  Marine ,
  GrayishPink ,
  PaleTurquoise ,
  PastelYellow ,
  BlueyPurple ,
  CanaryYellow ,
  FadedRed ,
  Sepia ,
  Coffee ,
  BrightMagenta ,
  Mocha ,
  Ecru ,
  Purpleish ,
  Cranberry ,
  DarkishGreen ,
  BrownOrange ,
  DuskyRose ,
  Melon ,
  SicklyGreen ,
  Silver ,
  PurplyBlue ,
  PurpleishBlue ,
  HospitalGreen ,
  ShitBrown ,
  MidBlue ,
  Amber ,
  EasterGreen ,
  SoftBlue ,
  CeruleanBlue ,
  GoldenBrown ,
  BrightTurquoise ,
  RedPink ,
  RedPurple ,
  GrayishBrown ,
  Vermillion ,
  Russet ,
  SteelGray ,
  LighterPurple ,
  BrightViolet ,
  PrussianBlue ,
  SlateGreen ,
  DirtyPink ,
  DarkBlueGreen ,
  Pine ,
  YellowyGreen ,
  DarkGold ,
  Bluish ,
  DarkishBlue ,
  DullRed ,
  PinkyRed ,
  Bronze ,
  PaleTeal ,
  MilitaryGreen ,
  BarbiePink ,
  BubblegumPink ,
  PeaSoupGreen ,
  DarkMustard ,
  Shit ,
  MediumPurple ,
  VeryDarkGreen ,
  Dirt ,
  DuskyPink ,
  RedViolet ,
  LemonYellow ,
  Pistachio ,
  DullYellow ,
  DarkLimeGreen ,
  DenimBlue ,
  TealBlue ,
  LightishBlue ,
  PurpleyBlue ,
  LightIndigo ,
  SwampGreen ,
  BrownGreen ,
  DarkMaroon ,
  HotPurple ,
  DarkForestGreen ,
  FadedBlue ,
  DrabGreen ,
  LightLimeGreen ,
  SnotGreen ,
  Yellowish ,
  LightBlueGreen ,
  Bordeaux ,
  LightMauve ,
  Ocean ,
  Marigold ,
  MuddyGreen ,
  DullOrange ,
  Steel ,
  ElectricPurple ,
  FluorescentGreen ,
  YellowishBrown ,
  Blush ,
  SoftGreen ,
  BrightOrange ,
  Lemon ,
  PurpleGray ,
  AcidGreen ,
  PaleLavender ,
  VioletBlue ,
  LightForestGreen ,
  BurntRed ,
  KhakiGreen ,
  Cerise ,
  FadedPurple ,
  Apricot ,
  DarkOliveGreen ,
  GrayBrown ,
  GreenGray ,
  TrueBlue ,
  PaleViolet ,
  PeriwinkleBlue ,
  LightSkyBlue ,
  Blurple ,
  GreenBrown ,
  Bluegreen ,
  BrightTeal ,
  BrownishYellow ,
  PeaSoup ,
  Forest ,
  BarneyPurple ,
  Ultramarine ,
  Purplish ,
  PukeYellow ,
  BluishGray ,
  DarkPeriwinkle ,
  DarkLilac ,
  Reddish ,
  LightMaroon ,
  DustyPurple ,
  TerraCotta ,
  Avocado ,
  MarineBlue ,
  TealGreen ,
  SlateGray ,
  LighterGreen ,
  ElectricGreen ,
  DustyBlue ,
  GoldenYellow ,
  BrightYellow ,
  LightLavender ,
  Umber ,
  Poop ,
  DarkPeach ,
  JungleGreen ,
  Eggshell ,
  Denim ,
  YellowBrown ,
  DullPurple ,
  ChocolateBrown ,
  WineRed ,
  NeonBlue ,
  DirtyGreen ,
  LightTan ,
  IceBlue ,
  CadetBlue ,
  DarkMauve ,
  VeryLightBlue ,
  GrayPurple ,
  PastelPink ,
  VeryLightGreen ,
  DarkSkyBlue ,
  Evergreen ,
  DullPink ,
  Aubergine ,
  Mahogany ,
  ReddishOrange ,
  DeepGreen ,
  VomitGreen ,
  PurplePink ,
  DustyPink ,
  FadedGreen ,
  CamoGreen ,
  PinkyPurple ,
  PinkPurple ,
  BrownishRed ,
  DarkRose ,
  Mud ,
  Brownish ,
  EmeraldGreen ,
  PaleBrown ,
  DullBlue ,
  BurntUmber ,
  MediumGreen ,
  Clay ,
  LightAqua ,
  LightOliveGreen ,
  BrownishOrange ,
  DarkAqua ,
  PurplishPink ,
  DarkSalmon ,
  GreenishGray ,
  Jade ,
  UglyGreen ,
  DarkBeige ,
  Emerald ,
  PaleRed ,
  LightMagenta ,
  Sky ,
  LightCyan ,
  YellowOrange ,
  ReddishPurple ,
  ReddishPink ,
  Orchid ,
  DirtyYellow ,
  OrangeRed ,
  DeepRed ,
  OrangeBrown ,
  CobaltBlue ,
  NeonPink ,
  RosePink ,
  GrayishPurple ,
  Raspberry ,
  AquaGreen ,
  SalmonPink ,
  Tangerine ,
  BrownishGreen ,
  RedBrown ,
  GreenishBrown ,
  Pumpkin ,
  PineGreen ,
  Charcoal ,
  BabyPink ,
  Cornflower ,
  BlueViolet ,
  Chocolate ,
  GrayishGreen ,
  Scarlet ,
  GreenYellow ,
  DarkOlive ,
  Sienna ,
  PastelPurple ,
  Terracotta ,
  AquaBlue ,
  SageGreen ,
  BloodRed ,
  DeepPink ,
  Grass ,
  Moss ,
  PastelBlue ,
  BluishGreen ,
  GreenBlue ,
  DarkTan ,
  GreenishBlue ,
  PaleOrange ,
  Vomit ,
  ForrestGreen ,
  DarkLavender ,
  DarkViolet ,
  PurpleBlue ,
  DarkCyan ,
  OliveDrab ,
  Pinkish ,
  Cobalt ,
  NeonPurple ,
  LightTurquoise ,
  AppleGreen ,
  DullGreen ,
  Wine ,
  PowderBlue ,
  OffWhite ,
  ElectricBlue ,
  DarkTurquoise ,
  BluePurple ,
  Azure ,
  BrightRed ,
  PinkishRed ,
  CornflowerBlue ,
  LightOlive ,
  Grape ,
  GrayishBlue ,
  PurplishBlue ,
  YellowishGreen ,
  GreenishYellow ,
  MediumBlue ,
  DustyRose ,
  LightViolet ,
  MidnightBlue ,
  BluishPurple ,
  RedOrange ,
  DarkMagenta ,
  Greenish ,
  OceanBlue ,
  Coral ,
  Cream ,
  ReddishBrown ,
  BurntSienna ,
  Brick ,
  Sage ,
  GrayGreen ,
  White ,
  RobinSEggBlue ,
  MossGreen ,
  SteelBlue ,
  Eggplant ,
  LightYellow ,
  LeafGreen ,
  LightGray ,
  Puke ,
  PinkishPurple ,
  SeaBlue ,
  PalePurple ,
  SlateBlue ,
  BlueGray ,
  HunterGreen ,
  Fuchsia ,
  Crimson ,
  PaleYellow ,
  Ochre ,
  MustardYellow ,
  LightRed ,
  Cerulean ,
  PalePink ,
  DeepBlue ,
  Rust ,
  LightTeal ,
  Slate ,
  Goldenrod ,
  DarkYellow ,
  DarkGray ,
  ArmyGreen ,
  GrayBlue ,
  Seafoam ,
  Puce ,
  SpringGreen ,
  DarkOrange ,
  Sand ,
  PastelGreen ,
  Mint ,
  LightOrange ,
  BrightPink ,
  Chartreuse ,
  DeepPurple ,
  DarkBrown ,
  Taupe ,
  PeaGreen ,
  PukeGreen ,
  KellyGreen ,
  SeafoamGreen ,
  BlueGreen ,
  Khaki ,
  Burgundy ,
  DarkTeal ,
  BrickRed ,
  RoyalPurple ,
  Plum ,
  MintGreen ,
  Gold ,
  BabyBlue ,
  YellowGreen ,
  BrightPurple ,
  DarkRed ,
  PaleBlue ,
  GrassGreen ,
  Navy ,
  Aquamarine ,
  BurntOrange ,
  NeonGreen ,
  BrightBlue ,
  Rose ,
  LightPink ,
  Mustard ,
  Indigo ,
  Lime ,
  SeaGreen ,
  Periwinkle ,
  DarkPink ,
  OliveGreen ,
  Peach ,
  PaleGreen ,
  LightBrown ,
  HotPink ,
  Black ,
  Lilac ,
  NavyBlue ,
  RoyalBlue ,
  Beige ,
  Salmon ,
  Olive ,
  Maroon ,
  BrightGreen ,
  DarkPurple ,
  Mauve ,
  ForestGreen ,
  Aqua ,
  Cyan ,
  Tan ,
  DarkBlue ,
  Lavender ,
  Turquoise ,
  DarkGreen ,
  Violet ,
  LightPurple ,
  LimeGreen ,
  Gray ,
  SkyBlue ,
  Yellow ,
  Magenta ,
  LightGreen ,
  Orange ,
  Teal ,
  LightBlue ,
  Red ,
  Brown ,
  Pink ,
  Blue ,
  Green ,
  Purple ,
  MAX_VALUE
};

BEGIN_ENUM_LIST(Color)
  ENUM_VALUE(Color, CloudyBlue)
  ENUM_VALUE(Color, DarkPastelGreen)
  ENUM_VALUE(Color, Dust)
  ENUM_VALUE(Color, ElectricLime)
  ENUM_VALUE(Color, FreshGreen)
  ENUM_VALUE(Color, LightEggplant)
  ENUM_VALUE(Color, NastyGreen)
  ENUM_VALUE(Color, ReallyLightBlue)
  ENUM_VALUE(Color, Tea)
  ENUM_VALUE(Color, WarmPurple)
  ENUM_VALUE(Color, YellowishTan)
  ENUM_VALUE(Color, Cement)
  ENUM_VALUE(Color, DarkGrassGreen)
  ENUM_VALUE(Color, DustyTeal)
  ENUM_VALUE(Color, GrayTeal)
  ENUM_VALUE(Color, MacaroniAndCheese)
  ENUM_VALUE(Color, PinkishTan)
  ENUM_VALUE(Color, Spruce)
  ENUM_VALUE(Color, StrongBlue)
  ENUM_VALUE(Color, ToxicGreen)
  ENUM_VALUE(Color, WindowsBlue)
  ENUM_VALUE(Color, BlueBlue)
  ENUM_VALUE(Color, BlueWithAHintOfPurple)
  ENUM_VALUE(Color, Booger)
  ENUM_VALUE(Color, BrightSeaGreen)
  ENUM_VALUE(Color, DarkGreenBlue)
  ENUM_VALUE(Color, DeepTurquoise)
  ENUM_VALUE(Color, GreenTeal)
  ENUM_VALUE(Color, StrongPink)
  ENUM_VALUE(Color, Bland)
  ENUM_VALUE(Color, DeepAqua)
  ENUM_VALUE(Color, LavenderPink)
  ENUM_VALUE(Color, LightMossGreen)
  ENUM_VALUE(Color, LightSeafoamGreen)
  ENUM_VALUE(Color, OliveYellow)
  ENUM_VALUE(Color, PigPink)
  ENUM_VALUE(Color, DeepLilac)
  ENUM_VALUE(Color, Desert)
  ENUM_VALUE(Color, DustyLavender)
  ENUM_VALUE(Color, PurpleyGray)
  ENUM_VALUE(Color, Purply)
  ENUM_VALUE(Color, CandyPink)
  ENUM_VALUE(Color, LightPastelGreen)
  ENUM_VALUE(Color, BoringGreen)
  ENUM_VALUE(Color, KiwiGreen)
  ENUM_VALUE(Color, LightGrayGreen)
  ENUM_VALUE(Color, OrangePink)
  ENUM_VALUE(Color, TeaGreen)
  ENUM_VALUE(Color, VeryLightBrown)
  ENUM_VALUE(Color, EggShell)
  ENUM_VALUE(Color, EggplantPurple)
  ENUM_VALUE(Color, PowderPink)
  ENUM_VALUE(Color, ReddishGray)
  ENUM_VALUE(Color, BabyShitBrown)
  ENUM_VALUE(Color, Liliac)
  ENUM_VALUE(Color, StormyBlue)
  ENUM_VALUE(Color, UglyBrown)
  ENUM_VALUE(Color, Custard)
  ENUM_VALUE(Color, DarkishPink)
  ENUM_VALUE(Color, DeepBrown)
  ENUM_VALUE(Color, GreenishBeige)
  ENUM_VALUE(Color, Manilla)
  ENUM_VALUE(Color, OffBlue)
  ENUM_VALUE(Color, BattleshipGray)
  ENUM_VALUE(Color, BrownyGreen)
  ENUM_VALUE(Color, Bruise)
  ENUM_VALUE(Color, KelleyGreen)
  ENUM_VALUE(Color, SicklyYellow)
  ENUM_VALUE(Color, SunnyYellow)
  ENUM_VALUE(Color, Azul)
  ENUM_VALUE(Color, Darkgreen)
  ENUM_VALUE(Color, GreenOrYellow)
  ENUM_VALUE(Color, Lichen)
  ENUM_VALUE(Color, LightLightGreen)
  ENUM_VALUE(Color, PaleGold)
  ENUM_VALUE(Color, SunYellow)
  ENUM_VALUE(Color, TanGreen)
  ENUM_VALUE(Color, Burple)
  ENUM_VALUE(Color, Butterscotch)
  ENUM_VALUE(Color, Toupe)
  ENUM_VALUE(Color, DarkCream)
  ENUM_VALUE(Color, IndianRed)
  ENUM_VALUE(Color, LightLavendar)
  ENUM_VALUE(Color, PoisonGreen)
  ENUM_VALUE(Color, BabyPukeGreen)
  ENUM_VALUE(Color, BrightYellowGreen)
  ENUM_VALUE(Color, CharcoalGray)
  ENUM_VALUE(Color, Squash)
  ENUM_VALUE(Color, Cinnamon)
  ENUM_VALUE(Color, LightPeaGreen)
  ENUM_VALUE(Color, RadioactiveGreen)
  ENUM_VALUE(Color, RawSienna)
  ENUM_VALUE(Color, BabyPurple)
  ENUM_VALUE(Color, Cocoa)
  ENUM_VALUE(Color, LightRoyalBlue)
  ENUM_VALUE(Color, Orangeish)
  ENUM_VALUE(Color, RustBrown)
  ENUM_VALUE(Color, SandBrown)
  ENUM_VALUE(Color, Swamp)
  ENUM_VALUE(Color, TealishGreen)
  ENUM_VALUE(Color, BurntSiena)
  ENUM_VALUE(Color, Camo)
  ENUM_VALUE(Color, DuskBlue)
  ENUM_VALUE(Color, Fern)
  ENUM_VALUE(Color, OldRose)
  ENUM_VALUE(Color, PaleLightGreen)
  ENUM_VALUE(Color, PeachyPink)
  ENUM_VALUE(Color, RosyPink)
  ENUM_VALUE(Color, LightBluishGreen)
  ENUM_VALUE(Color, LightBrightGreen)
  ENUM_VALUE(Color, LightNeonGreen)
  ENUM_VALUE(Color, LightSeafoam)
  ENUM_VALUE(Color, TiffanyBlue)
  ENUM_VALUE(Color, WashedOutGreen)
  ENUM_VALUE(Color, BrownyOrange)
  ENUM_VALUE(Color, NiceBlue)
  ENUM_VALUE(Color, Sapphire)
  ENUM_VALUE(Color, GrayishTeal)
  ENUM_VALUE(Color, OrangeyYellow)
  ENUM_VALUE(Color, Parchment)
  ENUM_VALUE(Color, Straw)
  ENUM_VALUE(Color, VeryDarkBrown)
  ENUM_VALUE(Color, Terracota)
  ENUM_VALUE(Color, UglyBlue)
  ENUM_VALUE(Color, ClearBlue)
  ENUM_VALUE(Color, Creme)
  ENUM_VALUE(Color, FoamGreen)
  ENUM_VALUE(Color, GrayOrGreen)
  ENUM_VALUE(Color, LightGold)
  ENUM_VALUE(Color, SeafoamBlue)
  ENUM_VALUE(Color, Topaz)
  ENUM_VALUE(Color, VioletPink)
  ENUM_VALUE(Color, Wintergreen)
  ENUM_VALUE(Color, YellowTan)
  ENUM_VALUE(Color, DarkFuchsia)
  ENUM_VALUE(Color, IndigoBlue)
  ENUM_VALUE(Color, LightYellowishGreen)
  ENUM_VALUE(Color, PaleMagenta)
  ENUM_VALUE(Color, RichPurple)
  ENUM_VALUE(Color, SunflowerYellow)
  ENUM_VALUE(Color, GreenOrBlue)
  ENUM_VALUE(Color, Leather)
  ENUM_VALUE(Color, RacingGreen)
  ENUM_VALUE(Color, VividPurple)
  ENUM_VALUE(Color, DarkRoyalBlue)
  ENUM_VALUE(Color, Hazel)
  ENUM_VALUE(Color, MutedPink)
  ENUM_VALUE(Color, BoogerGreen)
  ENUM_VALUE(Color, Canary)
  ENUM_VALUE(Color, CoolGray)
  ENUM_VALUE(Color, DarkTaupe)
  ENUM_VALUE(Color, DarkishPurple)
  ENUM_VALUE(Color, TrueGreen)
  ENUM_VALUE(Color, CoralPink)
  ENUM_VALUE(Color, DarkSage)
  ENUM_VALUE(Color, DarkSlateBlue)
  ENUM_VALUE(Color, FlatBlue)
  ENUM_VALUE(Color, Mushroom)
  ENUM_VALUE(Color, RichBlue)
  ENUM_VALUE(Color, DirtyPurple)
  ENUM_VALUE(Color, Greenblue)
  ENUM_VALUE(Color, IckyGreen)
  ENUM_VALUE(Color, LightKhaki)
  ENUM_VALUE(Color, WarmBlue)
  ENUM_VALUE(Color, DarkHotPink)
  ENUM_VALUE(Color, DeepSeaBlue)
  ENUM_VALUE(Color, Carmine)
  ENUM_VALUE(Color, DarkYellowGreen)
  ENUM_VALUE(Color, PalePeach)
  ENUM_VALUE(Color, PlumPurple)
  ENUM_VALUE(Color, GoldenRod)
  ENUM_VALUE(Color, NeonRed)
  ENUM_VALUE(Color, OldPink)
  ENUM_VALUE(Color, VeryPaleBlue)
  ENUM_VALUE(Color, BloodOrange)
  ENUM_VALUE(Color, Grapefruit)
  ENUM_VALUE(Color, SandYellow)
  ENUM_VALUE(Color, ClayBrown)
  ENUM_VALUE(Color, DarkBlueGray)
  ENUM_VALUE(Color, FlatGreen)
  ENUM_VALUE(Color, LightGreenBlue)
  ENUM_VALUE(Color, WarmPink)
  ENUM_VALUE(Color, DodgerBlue)
  ENUM_VALUE(Color, GrossGreen)
  ENUM_VALUE(Color, Ice)
  ENUM_VALUE(Color, MetallicBlue)
  ENUM_VALUE(Color, PaleSalmon)
  ENUM_VALUE(Color, SapGreen)
  ENUM_VALUE(Color, Algae)
  ENUM_VALUE(Color, BlueyGray)
  ENUM_VALUE(Color, GreenyGray)
  ENUM_VALUE(Color, HighlighterGreen)
  ENUM_VALUE(Color, LightLightBlue)
  ENUM_VALUE(Color, LightMint)
  ENUM_VALUE(Color, RawUmber)
  ENUM_VALUE(Color, VividBlue)
  ENUM_VALUE(Color, DeepLavender)
  ENUM_VALUE(Color, DullTeal)
  ENUM_VALUE(Color, LightGreenishBlue)
  ENUM_VALUE(Color, MudGreen)
  ENUM_VALUE(Color, Pinky)
  ENUM_VALUE(Color, RedWine)
  ENUM_VALUE(Color, ShitGreen)
  ENUM_VALUE(Color, TanBrown)
  ENUM_VALUE(Color, Darkblue)
  ENUM_VALUE(Color, Rosa)
  ENUM_VALUE(Color, Lipstick)
  ENUM_VALUE(Color, PaleMauve)
  ENUM_VALUE(Color, Claret)
  ENUM_VALUE(Color, Dandelion)
  ENUM_VALUE(Color, Orangered)
  ENUM_VALUE(Color, PoopGreen)
  ENUM_VALUE(Color, Ruby)
  ENUM_VALUE(Color, Dark)
  ENUM_VALUE(Color, GreenishTurquoise)
  ENUM_VALUE(Color, PastelRed)
  ENUM_VALUE(Color, PissYellow)
  ENUM_VALUE(Color, BrightCyan)
  ENUM_VALUE(Color, DarkCoral)
  ENUM_VALUE(Color, AlgaeGreen)
  ENUM_VALUE(Color, DarkishRed)
  ENUM_VALUE(Color, ReddyBrown)
  ENUM_VALUE(Color, BlushPink)
  ENUM_VALUE(Color, CamouflageGreen)
  ENUM_VALUE(Color, LawnGreen)
  ENUM_VALUE(Color, Putty)
  ENUM_VALUE(Color, VibrantBlue)
  ENUM_VALUE(Color, DarkSand)
  ENUM_VALUE(Color, PurpleOrBlue)
  ENUM_VALUE(Color, Saffron)
  ENUM_VALUE(Color, Twilight)
  ENUM_VALUE(Color, WarmBrown)
  ENUM_VALUE(Color, Bluegray)
  ENUM_VALUE(Color, BubbleGumPink)
  ENUM_VALUE(Color, DuckEggBlue)
  ENUM_VALUE(Color, GreenishCyan)
  ENUM_VALUE(Color, Petrol)
  ENUM_VALUE(Color, Royal)
  ENUM_VALUE(Color, Butter)
  ENUM_VALUE(Color, DustyOrange)
  ENUM_VALUE(Color, OffYellow)
  ENUM_VALUE(Color, PaleOliveGreen)
  ENUM_VALUE(Color, Orangish)
  ENUM_VALUE(Color, Leaf)
  ENUM_VALUE(Color, LightBlueGray)
  ENUM_VALUE(Color, DriedBlood)
  ENUM_VALUE(Color, LightishPurple)
  ENUM_VALUE(Color, RustyRed)
  ENUM_VALUE(Color, LavenderBlue)
  ENUM_VALUE(Color, LightGrassGreen)
  ENUM_VALUE(Color, LightMintGreen)
  ENUM_VALUE(Color, Sunflower)
  ENUM_VALUE(Color, Velvet)
  ENUM_VALUE(Color, BrickOrange)
  ENUM_VALUE(Color, LightishRed)
  ENUM_VALUE(Color, PureBlue)
  ENUM_VALUE(Color, TwilightBlue)
  ENUM_VALUE(Color, VioletRed)
  ENUM_VALUE(Color, YellowyBrown)
  ENUM_VALUE(Color, Carnation)
  ENUM_VALUE(Color, MuddyYellow)
  ENUM_VALUE(Color, DarkSeafoamGreen)
  ENUM_VALUE(Color, DeepRose)
  ENUM_VALUE(Color, DustyRed)
  ENUM_VALUE(Color, GrayOrBlue)
  ENUM_VALUE(Color, LemonLime)
  ENUM_VALUE(Color, PurpleOrPink)
  ENUM_VALUE(Color, BrownYellow)
  ENUM_VALUE(Color, PurpleBrown)
  ENUM_VALUE(Color, Wisteria)
  ENUM_VALUE(Color, BananaYellow)
  ENUM_VALUE(Color, LipstickRed)
  ENUM_VALUE(Color, WaterBlue)
  ENUM_VALUE(Color, BrownGray)
  ENUM_VALUE(Color, VibrantPurple)
  ENUM_VALUE(Color, BabyGreen)
  ENUM_VALUE(Color, BarfGreen)
  ENUM_VALUE(Color, EggshellBlue)
  ENUM_VALUE(Color, SandyYellow)
  ENUM_VALUE(Color, CoolGreen)
  ENUM_VALUE(Color, Pale)
  ENUM_VALUE(Color, BlueOrGray)
  ENUM_VALUE(Color, HotMagenta)
  ENUM_VALUE(Color, Grayblue)
  ENUM_VALUE(Color, Purpley)
  ENUM_VALUE(Color, BabyShitGreen)
  ENUM_VALUE(Color, BrownishPink)
  ENUM_VALUE(Color, DarkAquamarine)
  ENUM_VALUE(Color, Diarrhea)
  ENUM_VALUE(Color, LightMustard)
  ENUM_VALUE(Color, PaleSkyBlue)
  ENUM_VALUE(Color, TurtleGreen)
  ENUM_VALUE(Color, BrightOlive)
  ENUM_VALUE(Color, DarkGrayBlue)
  ENUM_VALUE(Color, GreenyBrown)
  ENUM_VALUE(Color, LemonGreen)
  ENUM_VALUE(Color, LightPeriwinkle)
  ENUM_VALUE(Color, SeaweedGreen)
  ENUM_VALUE(Color, SunshineYellow)
  ENUM_VALUE(Color, UglyPurple)
  ENUM_VALUE(Color, MediumPink)
  ENUM_VALUE(Color, PukeBrown)
  ENUM_VALUE(Color, VeryLightPink)
  ENUM_VALUE(Color, Viridian)
  ENUM_VALUE(Color, Bile)
  ENUM_VALUE(Color, FadedYellow)
  ENUM_VALUE(Color, VeryPaleGreen)
  ENUM_VALUE(Color, VibrantGreen)
  ENUM_VALUE(Color, BrightLime)
  ENUM_VALUE(Color, Spearmint)
  ENUM_VALUE(Color, LightAquamarine)
  ENUM_VALUE(Color, LightSage)
  ENUM_VALUE(Color, Yellowgreen)
  ENUM_VALUE(Color, BabyPoo)
  ENUM_VALUE(Color, DarkSeafoam)
  ENUM_VALUE(Color, DeepTeal)
  ENUM_VALUE(Color, Heather)
  ENUM_VALUE(Color, RustOrange)
  ENUM_VALUE(Color, DirtyBlue)
  ENUM_VALUE(Color, FernGreen)
  ENUM_VALUE(Color, BrightLilac)
  ENUM_VALUE(Color, WeirdGreen)
  ENUM_VALUE(Color, PeacockBlue)
  ENUM_VALUE(Color, AvocadoGreen)
  ENUM_VALUE(Color, FadedOrange)
  ENUM_VALUE(Color, GrapePurple)
  ENUM_VALUE(Color, HotGreen)
  ENUM_VALUE(Color, LimeYellow)
  ENUM_VALUE(Color, Mango)
  ENUM_VALUE(Color, Shamrock)
  ENUM_VALUE(Color, Bubblegum)
  ENUM_VALUE(Color, PurplishBrown)
  ENUM_VALUE(Color, VomitYellow)
  ENUM_VALUE(Color, PaleCyan)
  ENUM_VALUE(Color, KeyLime)
  ENUM_VALUE(Color, TomatoRed)
  ENUM_VALUE(Color, Lightgreen)
  ENUM_VALUE(Color, Merlot)
  ENUM_VALUE(Color, NightBlue)
  ENUM_VALUE(Color, PurpleishPink)
  ENUM_VALUE(Color, Apple)
  ENUM_VALUE(Color, BabyPoopGreen)
  ENUM_VALUE(Color, GreenApple)
  ENUM_VALUE(Color, Heliotrope)
  ENUM_VALUE(Color, YellowOrGreen)
  ENUM_VALUE(Color, AlmostBlack)
  ENUM_VALUE(Color, CoolBlue)
  ENUM_VALUE(Color, LeafyGreen)
  ENUM_VALUE(Color, MustardBrown)
  ENUM_VALUE(Color, Dusk)
  ENUM_VALUE(Color, DullBrown)
  ENUM_VALUE(Color, FrogGreen)
  ENUM_VALUE(Color, VividGreen)
  ENUM_VALUE(Color, BrightLightGreen)
  ENUM_VALUE(Color, FluroGreen)
  ENUM_VALUE(Color, Kiwi)
  ENUM_VALUE(Color, Seaweed)
  ENUM_VALUE(Color, NavyGreen)
  ENUM_VALUE(Color, UltramarineBlue)
  ENUM_VALUE(Color, Iris)
  ENUM_VALUE(Color, PastelOrange)
  ENUM_VALUE(Color, YellowishOrange)
  ENUM_VALUE(Color, Perrywinkle)
  ENUM_VALUE(Color, Tealish)
  ENUM_VALUE(Color, DarkPlum)
  ENUM_VALUE(Color, Pear)
  ENUM_VALUE(Color, PinkishOrange)
  ENUM_VALUE(Color, MidnightPurple)
  ENUM_VALUE(Color, LightUrple)
  ENUM_VALUE(Color, DarkMint)
  ENUM_VALUE(Color, GreenishTan)
  ENUM_VALUE(Color, LightBurgundy)
  ENUM_VALUE(Color, TurquoiseBlue)
  ENUM_VALUE(Color, UglyPink)
  ENUM_VALUE(Color, Sandy)
  ENUM_VALUE(Color, ElectricPink)
  ENUM_VALUE(Color, MutedPurple)
  ENUM_VALUE(Color, MidGreen)
  ENUM_VALUE(Color, Grayish)
  ENUM_VALUE(Color, NeonYellow)
  ENUM_VALUE(Color, Banana)
  ENUM_VALUE(Color, CarnationPink)
  ENUM_VALUE(Color, Tomato)
  ENUM_VALUE(Color, Sea)
  ENUM_VALUE(Color, MuddyBrown)
  ENUM_VALUE(Color, TurquoiseGreen)
  ENUM_VALUE(Color, Buff)
  ENUM_VALUE(Color, Fawn)
  ENUM_VALUE(Color, MutedBlue)
  ENUM_VALUE(Color, PaleRose)
  ENUM_VALUE(Color, DarkMintGreen)
  ENUM_VALUE(Color, Amethyst)
  ENUM_VALUE(Color, BlueOrGreen)
  ENUM_VALUE(Color, Chestnut)
  ENUM_VALUE(Color, SickGreen)
  ENUM_VALUE(Color, Pea)
  ENUM_VALUE(Color, RustyOrange)
  ENUM_VALUE(Color, Stone)
  ENUM_VALUE(Color, RoseRed)
  ENUM_VALUE(Color, PaleAqua)
  ENUM_VALUE(Color, DeepOrange)
  ENUM_VALUE(Color, Earth)
  ENUM_VALUE(Color, MossyGreen)
  ENUM_VALUE(Color, GrassyGreen)
  ENUM_VALUE(Color, PaleLimeGreen)
  ENUM_VALUE(Color, LightGrayBlue)
  ENUM_VALUE(Color, PaleGray)
  ENUM_VALUE(Color, Asparagus)
  ENUM_VALUE(Color, Blueberry)
  ENUM_VALUE(Color, PurpleRed)
  ENUM_VALUE(Color, PaleLime)
  ENUM_VALUE(Color, GreenishTeal)
  ENUM_VALUE(Color, Caramel)
  ENUM_VALUE(Color, DeepMagenta)
  ENUM_VALUE(Color, LightPeach)
  ENUM_VALUE(Color, MilkChocolate)
  ENUM_VALUE(Color, Ocher)
  ENUM_VALUE(Color, OffGreen)
  ENUM_VALUE(Color, PurplyPink)
  ENUM_VALUE(Color, Lightblue)
  ENUM_VALUE(Color, DuskyBlue)
  ENUM_VALUE(Color, Golden)
  ENUM_VALUE(Color, LightBeige)
  ENUM_VALUE(Color, ButterYellow)
  ENUM_VALUE(Color, DuskyPurple)
  ENUM_VALUE(Color, FrenchBlue)
  ENUM_VALUE(Color, UglyYellow)
  ENUM_VALUE(Color, GreenyYellow)
  ENUM_VALUE(Color, OrangishRed)
  ENUM_VALUE(Color, ShamrockGreen)
  ENUM_VALUE(Color, OrangishBrown)
  ENUM_VALUE(Color, TreeGreen)
  ENUM_VALUE(Color, DeepViolet)
  ENUM_VALUE(Color, Gunmetal)
  ENUM_VALUE(Color, BlueOrPurple)
  ENUM_VALUE(Color, Cherry)
  ENUM_VALUE(Color, SandyBrown)
  ENUM_VALUE(Color, WarmGray)
  ENUM_VALUE(Color, DarkIndigo)
  ENUM_VALUE(Color, Midnight)
  ENUM_VALUE(Color, BlueyGreen)
  ENUM_VALUE(Color, GrayPink)
  ENUM_VALUE(Color, SoftPurple)
  ENUM_VALUE(Color, Blood)
  ENUM_VALUE(Color, BrownRed)
  ENUM_VALUE(Color, MediumGray)
  ENUM_VALUE(Color, Berry)
  ENUM_VALUE(Color, Poo)
  ENUM_VALUE(Color, PurpleyPink)
  ENUM_VALUE(Color, LightSalmon)
  ENUM_VALUE(Color, Snot)
  ENUM_VALUE(Color, EasterPurple)
  ENUM_VALUE(Color, LightYellowGreen)
  ENUM_VALUE(Color, DarkNavyBlue)
  ENUM_VALUE(Color, Drab)
  ENUM_VALUE(Color, LightRose)
  ENUM_VALUE(Color, Rouge)
  ENUM_VALUE(Color, PurplishRed)
  ENUM_VALUE(Color, SlimeGreen)
  ENUM_VALUE(Color, BabyPoop)
  ENUM_VALUE(Color, IrishGreen)
  ENUM_VALUE(Color, PinkOrPurple)
  ENUM_VALUE(Color, DarkNavy)
  ENUM_VALUE(Color, GreenyBlue)
  ENUM_VALUE(Color, LightPlum)
  ENUM_VALUE(Color, PinkishGray)
  ENUM_VALUE(Color, DirtyOrange)
  ENUM_VALUE(Color, RustRed)
  ENUM_VALUE(Color, PaleLilac)
  ENUM_VALUE(Color, OrangeyRed)
  ENUM_VALUE(Color, PrimaryBlue)
  ENUM_VALUE(Color, KermitGreen)
  ENUM_VALUE(Color, BrownishPurple)
  ENUM_VALUE(Color, MurkyGreen)
  ENUM_VALUE(Color, Wheat)
  ENUM_VALUE(Color, VeryDarkPurple)
  ENUM_VALUE(Color, BottleGreen)
  ENUM_VALUE(Color, Watermelon)
  ENUM_VALUE(Color, DeepSkyBlue)
  ENUM_VALUE(Color, FireEngineRed)
  ENUM_VALUE(Color, YellowOchre)
  ENUM_VALUE(Color, PumpkinOrange)
  ENUM_VALUE(Color, PaleOlive)
  ENUM_VALUE(Color, LightLilac)
  ENUM_VALUE(Color, LightishGreen)
  ENUM_VALUE(Color, CarolinaBlue)
  ENUM_VALUE(Color, Mulberry)
  ENUM_VALUE(Color, ShockingPink)
  ENUM_VALUE(Color, Auburn)
  ENUM_VALUE(Color, BrightLimeGreen)
  ENUM_VALUE(Color, Celadon)
  ENUM_VALUE(Color, PinkishBrown)
  ENUM_VALUE(Color, PooBrown)
  ENUM_VALUE(Color, BrightSkyBlue)
  ENUM_VALUE(Color, Celery)
  ENUM_VALUE(Color, DirtBrown)
  ENUM_VALUE(Color, Strawberry)
  ENUM_VALUE(Color, DarkLime)
  ENUM_VALUE(Color, Copper)
  ENUM_VALUE(Color, MediumBrown)
  ENUM_VALUE(Color, MutedGreen)
  ENUM_VALUE(Color, RobinSEgg)
  ENUM_VALUE(Color, BrightAqua)
  ENUM_VALUE(Color, BrightLavender)
  ENUM_VALUE(Color, Ivory)
  ENUM_VALUE(Color, VeryLightPurple)
  ENUM_VALUE(Color, LightNavy)
  ENUM_VALUE(Color, PinkRed)
  ENUM_VALUE(Color, OliveBrown)
  ENUM_VALUE(Color, PoopBrown)
  ENUM_VALUE(Color, MustardGreen)
  ENUM_VALUE(Color, OceanGreen)
  ENUM_VALUE(Color, VeryDarkBlue)
  ENUM_VALUE(Color, DustyGreen)
  ENUM_VALUE(Color, LightNavyBlue)
  ENUM_VALUE(Color, MintyGreen)
  ENUM_VALUE(Color, Adobe)
  ENUM_VALUE(Color, Barney)
  ENUM_VALUE(Color, JadeGreen)
  ENUM_VALUE(Color, BrightLightBlue)
  ENUM_VALUE(Color, LightLime)
  ENUM_VALUE(Color, DarkKhaki)
  ENUM_VALUE(Color, OrangeYellow)
  ENUM_VALUE(Color, Ocre)
  ENUM_VALUE(Color, Maize)
  ENUM_VALUE(Color, FadedPink)
  ENUM_VALUE(Color, BritishRacingGreen)
  ENUM_VALUE(Color, Sandstone)
  ENUM_VALUE(Color, MudBrown)
  ENUM_VALUE(Color, LightSeaGreen)
  ENUM_VALUE(Color, RobinEggBlue)
  ENUM_VALUE(Color, AquaMarine)
  ENUM_VALUE(Color, DarkSeaGreen)
  ENUM_VALUE(Color, SoftPink)
  ENUM_VALUE(Color, OrangeyBrown)
  ENUM_VALUE(Color, CherryRed)
  ENUM_VALUE(Color, BurntYellow)
  ENUM_VALUE(Color, BrownishGray)
  ENUM_VALUE(Color, Camel)
  ENUM_VALUE(Color, PurplishGray)
  ENUM_VALUE(Color, Marine)
  ENUM_VALUE(Color, GrayishPink)
  ENUM_VALUE(Color, PaleTurquoise)
  ENUM_VALUE(Color, PastelYellow)
  ENUM_VALUE(Color, BlueyPurple)
  ENUM_VALUE(Color, CanaryYellow)
  ENUM_VALUE(Color, FadedRed)
  ENUM_VALUE(Color, Sepia)
  ENUM_VALUE(Color, Coffee)
  ENUM_VALUE(Color, BrightMagenta)
  ENUM_VALUE(Color, Mocha)
  ENUM_VALUE(Color, Ecru)
  ENUM_VALUE(Color, Purpleish)
  ENUM_VALUE(Color, Cranberry)
  ENUM_VALUE(Color, DarkishGreen)
  ENUM_VALUE(Color, BrownOrange)
  ENUM_VALUE(Color, DuskyRose)
  ENUM_VALUE(Color, Melon)
  ENUM_VALUE(Color, SicklyGreen)
  ENUM_VALUE(Color, Silver)
  ENUM_VALUE(Color, PurplyBlue)
  ENUM_VALUE(Color, PurpleishBlue)
  ENUM_VALUE(Color, HospitalGreen)
  ENUM_VALUE(Color, ShitBrown)
  ENUM_VALUE(Color, MidBlue)
  ENUM_VALUE(Color, Amber)
  ENUM_VALUE(Color, EasterGreen)
  ENUM_VALUE(Color, SoftBlue)
  ENUM_VALUE(Color, CeruleanBlue)
  ENUM_VALUE(Color, GoldenBrown)
  ENUM_VALUE(Color, BrightTurquoise)
  ENUM_VALUE(Color, RedPink)
  ENUM_VALUE(Color, RedPurple)
  ENUM_VALUE(Color, GrayishBrown)
  ENUM_VALUE(Color, Vermillion)
  ENUM_VALUE(Color, Russet)
  ENUM_VALUE(Color, SteelGray)
  ENUM_VALUE(Color, LighterPurple)
  ENUM_VALUE(Color, BrightViolet)
  ENUM_VALUE(Color, PrussianBlue)
  ENUM_VALUE(Color, SlateGreen)
  ENUM_VALUE(Color, DirtyPink)
  ENUM_VALUE(Color, DarkBlueGreen)
  ENUM_VALUE(Color, Pine)
  ENUM_VALUE(Color, YellowyGreen)
  ENUM_VALUE(Color, DarkGold)
  ENUM_VALUE(Color, Bluish)
  ENUM_VALUE(Color, DarkishBlue)
  ENUM_VALUE(Color, DullRed)
  ENUM_VALUE(Color, PinkyRed)
  ENUM_VALUE(Color, Bronze)
  ENUM_VALUE(Color, PaleTeal)
  ENUM_VALUE(Color, MilitaryGreen)
  ENUM_VALUE(Color, BarbiePink)
  ENUM_VALUE(Color, BubblegumPink)
  ENUM_VALUE(Color, PeaSoupGreen)
  ENUM_VALUE(Color, DarkMustard)
  ENUM_VALUE(Color, Shit)
  ENUM_VALUE(Color, MediumPurple)
  ENUM_VALUE(Color, VeryDarkGreen)
  ENUM_VALUE(Color, Dirt)
  ENUM_VALUE(Color, DuskyPink)
  ENUM_VALUE(Color, RedViolet)
  ENUM_VALUE(Color, LemonYellow)
  ENUM_VALUE(Color, Pistachio)
  ENUM_VALUE(Color, DullYellow)
  ENUM_VALUE(Color, DarkLimeGreen)
  ENUM_VALUE(Color, DenimBlue)
  ENUM_VALUE(Color, TealBlue)
  ENUM_VALUE(Color, LightishBlue)
  ENUM_VALUE(Color, PurpleyBlue)
  ENUM_VALUE(Color, LightIndigo)
  ENUM_VALUE(Color, SwampGreen)
  ENUM_VALUE(Color, BrownGreen)
  ENUM_VALUE(Color, DarkMaroon)
  ENUM_VALUE(Color, HotPurple)
  ENUM_VALUE(Color, DarkForestGreen)
  ENUM_VALUE(Color, FadedBlue)
  ENUM_VALUE(Color, DrabGreen)
  ENUM_VALUE(Color, LightLimeGreen)
  ENUM_VALUE(Color, SnotGreen)
  ENUM_VALUE(Color, Yellowish)
  ENUM_VALUE(Color, LightBlueGreen)
  ENUM_VALUE(Color, Bordeaux)
  ENUM_VALUE(Color, LightMauve)
  ENUM_VALUE(Color, Ocean)
  ENUM_VALUE(Color, Marigold)
  ENUM_VALUE(Color, MuddyGreen)
  ENUM_VALUE(Color, DullOrange)
  ENUM_VALUE(Color, Steel)
  ENUM_VALUE(Color, ElectricPurple)
  ENUM_VALUE(Color, FluorescentGreen)
  ENUM_VALUE(Color, YellowishBrown)
  ENUM_VALUE(Color, Blush)
  ENUM_VALUE(Color, SoftGreen)
  ENUM_VALUE(Color, BrightOrange)
  ENUM_VALUE(Color, Lemon)
  ENUM_VALUE(Color, PurpleGray)
  ENUM_VALUE(Color, AcidGreen)
  ENUM_VALUE(Color, PaleLavender)
  ENUM_VALUE(Color, VioletBlue)
  ENUM_VALUE(Color, LightForestGreen)
  ENUM_VALUE(Color, BurntRed)
  ENUM_VALUE(Color, KhakiGreen)
  ENUM_VALUE(Color, Cerise)
  ENUM_VALUE(Color, FadedPurple)
  ENUM_VALUE(Color, Apricot)
  ENUM_VALUE(Color, DarkOliveGreen)
  ENUM_VALUE(Color, GrayBrown)
  ENUM_VALUE(Color, GreenGray)
  ENUM_VALUE(Color, TrueBlue)
  ENUM_VALUE(Color, PaleViolet)
  ENUM_VALUE(Color, PeriwinkleBlue)
  ENUM_VALUE(Color, LightSkyBlue)
  ENUM_VALUE(Color, Blurple)
  ENUM_VALUE(Color, GreenBrown)
  ENUM_VALUE(Color, Bluegreen)
  ENUM_VALUE(Color, BrightTeal)
  ENUM_VALUE(Color, BrownishYellow)
  ENUM_VALUE(Color, PeaSoup)
  ENUM_VALUE(Color, Forest)
  ENUM_VALUE(Color, BarneyPurple)
  ENUM_VALUE(Color, Ultramarine)
  ENUM_VALUE(Color, Purplish)
  ENUM_VALUE(Color, PukeYellow)
  ENUM_VALUE(Color, BluishGray)
  ENUM_VALUE(Color, DarkPeriwinkle)
  ENUM_VALUE(Color, DarkLilac)
  ENUM_VALUE(Color, Reddish)
  ENUM_VALUE(Color, LightMaroon)
  ENUM_VALUE(Color, DustyPurple)
  ENUM_VALUE(Color, TerraCotta)
  ENUM_VALUE(Color, Avocado)
  ENUM_VALUE(Color, MarineBlue)
  ENUM_VALUE(Color, TealGreen)
  ENUM_VALUE(Color, SlateGray)
  ENUM_VALUE(Color, LighterGreen)
  ENUM_VALUE(Color, ElectricGreen)
  ENUM_VALUE(Color, DustyBlue)
  ENUM_VALUE(Color, GoldenYellow)
  ENUM_VALUE(Color, BrightYellow)
  ENUM_VALUE(Color, LightLavender)
  ENUM_VALUE(Color, Umber)
  ENUM_VALUE(Color, Poop)
  ENUM_VALUE(Color, DarkPeach)
  ENUM_VALUE(Color, JungleGreen)
  ENUM_VALUE(Color, Eggshell)
  ENUM_VALUE(Color, Denim)
  ENUM_VALUE(Color, YellowBrown)
  ENUM_VALUE(Color, DullPurple)
  ENUM_VALUE(Color, ChocolateBrown)
  ENUM_VALUE(Color, WineRed)
  ENUM_VALUE(Color, NeonBlue)
  ENUM_VALUE(Color, DirtyGreen)
  ENUM_VALUE(Color, LightTan)
  ENUM_VALUE(Color, IceBlue)
  ENUM_VALUE(Color, CadetBlue)
  ENUM_VALUE(Color, DarkMauve)
  ENUM_VALUE(Color, VeryLightBlue)
  ENUM_VALUE(Color, GrayPurple)
  ENUM_VALUE(Color, PastelPink)
  ENUM_VALUE(Color, VeryLightGreen)
  ENUM_VALUE(Color, DarkSkyBlue)
  ENUM_VALUE(Color, Evergreen)
  ENUM_VALUE(Color, DullPink)
  ENUM_VALUE(Color, Aubergine)
  ENUM_VALUE(Color, Mahogany)
  ENUM_VALUE(Color, ReddishOrange)
  ENUM_VALUE(Color, DeepGreen)
  ENUM_VALUE(Color, VomitGreen)
  ENUM_VALUE(Color, PurplePink)
  ENUM_VALUE(Color, DustyPink)
  ENUM_VALUE(Color, FadedGreen)
  ENUM_VALUE(Color, CamoGreen)
  ENUM_VALUE(Color, PinkyPurple)
  ENUM_VALUE(Color, PinkPurple)
  ENUM_VALUE(Color, BrownishRed)
  ENUM_VALUE(Color, DarkRose)
  ENUM_VALUE(Color, Mud)
  ENUM_VALUE(Color, Brownish)
  ENUM_VALUE(Color, EmeraldGreen)
  ENUM_VALUE(Color, PaleBrown)
  ENUM_VALUE(Color, DullBlue)
  ENUM_VALUE(Color, BurntUmber)
  ENUM_VALUE(Color, MediumGreen)
  ENUM_VALUE(Color, Clay)
  ENUM_VALUE(Color, LightAqua)
  ENUM_VALUE(Color, LightOliveGreen)
  ENUM_VALUE(Color, BrownishOrange)
  ENUM_VALUE(Color, DarkAqua)
  ENUM_VALUE(Color, PurplishPink)
  ENUM_VALUE(Color, DarkSalmon)
  ENUM_VALUE(Color, GreenishGray)
  ENUM_VALUE(Color, Jade)
  ENUM_VALUE(Color, UglyGreen)
  ENUM_VALUE(Color, DarkBeige)
  ENUM_VALUE(Color, Emerald)
  ENUM_VALUE(Color, PaleRed)
  ENUM_VALUE(Color, LightMagenta)
  ENUM_VALUE(Color, Sky)
  ENUM_VALUE(Color, LightCyan)
  ENUM_VALUE(Color, YellowOrange)
  ENUM_VALUE(Color, ReddishPurple)
  ENUM_VALUE(Color, ReddishPink)
  ENUM_VALUE(Color, Orchid)
  ENUM_VALUE(Color, DirtyYellow)
  ENUM_VALUE(Color, OrangeRed)
  ENUM_VALUE(Color, DeepRed)
  ENUM_VALUE(Color, OrangeBrown)
  ENUM_VALUE(Color, CobaltBlue)
  ENUM_VALUE(Color, NeonPink)
  ENUM_VALUE(Color, RosePink)
  ENUM_VALUE(Color, GrayishPurple)
  ENUM_VALUE(Color, Raspberry)
  ENUM_VALUE(Color, AquaGreen)
  ENUM_VALUE(Color, SalmonPink)
  ENUM_VALUE(Color, Tangerine)
  ENUM_VALUE(Color, BrownishGreen)
  ENUM_VALUE(Color, RedBrown)
  ENUM_VALUE(Color, GreenishBrown)
  ENUM_VALUE(Color, Pumpkin)
  ENUM_VALUE(Color, PineGreen)
  ENUM_VALUE(Color, Charcoal)
  ENUM_VALUE(Color, BabyPink)
  ENUM_VALUE(Color, Cornflower)
  ENUM_VALUE(Color, BlueViolet)
  ENUM_VALUE(Color, Chocolate)
  ENUM_VALUE(Color, GrayishGreen)
  ENUM_VALUE(Color, Scarlet)
  ENUM_VALUE(Color, GreenYellow)
  ENUM_VALUE(Color, DarkOlive)
  ENUM_VALUE(Color, Sienna)
  ENUM_VALUE(Color, PastelPurple)
  ENUM_VALUE(Color, Terracotta)
  ENUM_VALUE(Color, AquaBlue)
  ENUM_VALUE(Color, SageGreen)
  ENUM_VALUE(Color, BloodRed)
  ENUM_VALUE(Color, DeepPink)
  ENUM_VALUE(Color, Grass)
  ENUM_VALUE(Color, Moss)
  ENUM_VALUE(Color, PastelBlue)
  ENUM_VALUE(Color, BluishGreen)
  ENUM_VALUE(Color, GreenBlue)
  ENUM_VALUE(Color, DarkTan)
  ENUM_VALUE(Color, GreenishBlue)
  ENUM_VALUE(Color, PaleOrange)
  ENUM_VALUE(Color, Vomit)
  ENUM_VALUE(Color, ForrestGreen)
  ENUM_VALUE(Color, DarkLavender)
  ENUM_VALUE(Color, DarkViolet)
  ENUM_VALUE(Color, PurpleBlue)
  ENUM_VALUE(Color, DarkCyan)
  ENUM_VALUE(Color, OliveDrab)
  ENUM_VALUE(Color, Pinkish)
  ENUM_VALUE(Color, Cobalt)
  ENUM_VALUE(Color, NeonPurple)
  ENUM_VALUE(Color, LightTurquoise)
  ENUM_VALUE(Color, AppleGreen)
  ENUM_VALUE(Color, DullGreen)
  ENUM_VALUE(Color, Wine)
  ENUM_VALUE(Color, PowderBlue)
  ENUM_VALUE(Color, OffWhite)
  ENUM_VALUE(Color, ElectricBlue)
  ENUM_VALUE(Color, DarkTurquoise)
  ENUM_VALUE(Color, BluePurple)
  ENUM_VALUE(Color, Azure)
  ENUM_VALUE(Color, BrightRed)
  ENUM_VALUE(Color, PinkishRed)
  ENUM_VALUE(Color, CornflowerBlue)
  ENUM_VALUE(Color, LightOlive)
  ENUM_VALUE(Color, Grape)
  ENUM_VALUE(Color, GrayishBlue)
  ENUM_VALUE(Color, PurplishBlue)
  ENUM_VALUE(Color, YellowishGreen)
  ENUM_VALUE(Color, GreenishYellow)
  ENUM_VALUE(Color, MediumBlue)
  ENUM_VALUE(Color, DustyRose)
  ENUM_VALUE(Color, LightViolet)
  ENUM_VALUE(Color, MidnightBlue)
  ENUM_VALUE(Color, BluishPurple)
  ENUM_VALUE(Color, RedOrange)
  ENUM_VALUE(Color, DarkMagenta)
  ENUM_VALUE(Color, Greenish)
  ENUM_VALUE(Color, OceanBlue)
  ENUM_VALUE(Color, Coral)
  ENUM_VALUE(Color, Cream)
  ENUM_VALUE(Color, ReddishBrown)
  ENUM_VALUE(Color, BurntSienna)
  ENUM_VALUE(Color, Brick)
  ENUM_VALUE(Color, Sage)
  ENUM_VALUE(Color, GrayGreen)
  ENUM_VALUE(Color, White)
  ENUM_VALUE(Color, RobinSEggBlue)
  ENUM_VALUE(Color, MossGreen)
  ENUM_VALUE(Color, SteelBlue)
  ENUM_VALUE(Color, Eggplant)
  ENUM_VALUE(Color, LightYellow)
  ENUM_VALUE(Color, LeafGreen)
  ENUM_VALUE(Color, LightGray)
  ENUM_VALUE(Color, Puke)
  ENUM_VALUE(Color, PinkishPurple)
  ENUM_VALUE(Color, SeaBlue)
  ENUM_VALUE(Color, PalePurple)
  ENUM_VALUE(Color, SlateBlue)
  ENUM_VALUE(Color, BlueGray)
  ENUM_VALUE(Color, HunterGreen)
  ENUM_VALUE(Color, Fuchsia)
  ENUM_VALUE(Color, Crimson)
  ENUM_VALUE(Color, PaleYellow)
  ENUM_VALUE(Color, Ochre)
  ENUM_VALUE(Color, MustardYellow)
  ENUM_VALUE(Color, LightRed)
  ENUM_VALUE(Color, Cerulean)
  ENUM_VALUE(Color, PalePink)
  ENUM_VALUE(Color, DeepBlue)
  ENUM_VALUE(Color, Rust)
  ENUM_VALUE(Color, LightTeal)
  ENUM_VALUE(Color, Slate)
  ENUM_VALUE(Color, Goldenrod)
  ENUM_VALUE(Color, DarkYellow)
  ENUM_VALUE(Color, DarkGray)
  ENUM_VALUE(Color, ArmyGreen)
  ENUM_VALUE(Color, GrayBlue)
  ENUM_VALUE(Color, Seafoam)
  ENUM_VALUE(Color, Puce)
  ENUM_VALUE(Color, SpringGreen)
  ENUM_VALUE(Color, DarkOrange)
  ENUM_VALUE(Color, Sand)
  ENUM_VALUE(Color, PastelGreen)
  ENUM_VALUE(Color, Mint)
  ENUM_VALUE(Color, LightOrange)
  ENUM_VALUE(Color, BrightPink)
  ENUM_VALUE(Color, Chartreuse)
  ENUM_VALUE(Color, DeepPurple)
  ENUM_VALUE(Color, DarkBrown)
  ENUM_VALUE(Color, Taupe)
  ENUM_VALUE(Color, PeaGreen)
  ENUM_VALUE(Color, PukeGreen)
  ENUM_VALUE(Color, KellyGreen)
  ENUM_VALUE(Color, SeafoamGreen)
  ENUM_VALUE(Color, BlueGreen)
  ENUM_VALUE(Color, Khaki)
  ENUM_VALUE(Color, Burgundy)
  ENUM_VALUE(Color, DarkTeal)
  ENUM_VALUE(Color, BrickRed)
  ENUM_VALUE(Color, RoyalPurple)
  ENUM_VALUE(Color, Plum)
  ENUM_VALUE(Color, MintGreen)
  ENUM_VALUE(Color, Gold)
  ENUM_VALUE(Color, BabyBlue)
  ENUM_VALUE(Color, YellowGreen)
  ENUM_VALUE(Color, BrightPurple)
  ENUM_VALUE(Color, DarkRed)
  ENUM_VALUE(Color, PaleBlue)
  ENUM_VALUE(Color, GrassGreen)
  ENUM_VALUE(Color, Navy)
  ENUM_VALUE(Color, Aquamarine)
  ENUM_VALUE(Color, BurntOrange)
  ENUM_VALUE(Color, NeonGreen)
  ENUM_VALUE(Color, BrightBlue)
  ENUM_VALUE(Color, Rose)
  ENUM_VALUE(Color, LightPink)
  ENUM_VALUE(Color, Mustard)
  ENUM_VALUE(Color, Indigo)
  ENUM_VALUE(Color, Lime)
  ENUM_VALUE(Color, SeaGreen)
  ENUM_VALUE(Color, Periwinkle)
  ENUM_VALUE(Color, DarkPink)
  ENUM_VALUE(Color, OliveGreen)
  ENUM_VALUE(Color, Peach)
  ENUM_VALUE(Color, PaleGreen)
  ENUM_VALUE(Color, LightBrown)
  ENUM_VALUE(Color, HotPink)
  ENUM_VALUE(Color, Black)
  ENUM_VALUE(Color, Lilac)
  ENUM_VALUE(Color, NavyBlue)
  ENUM_VALUE(Color, RoyalBlue)
  ENUM_VALUE(Color, Beige)
  ENUM_VALUE(Color, Salmon)
  ENUM_VALUE(Color, Olive)
  ENUM_VALUE(Color, Maroon)
  ENUM_VALUE(Color, BrightGreen)
  ENUM_VALUE(Color, DarkPurple)
  ENUM_VALUE(Color, Mauve)
  ENUM_VALUE(Color, ForestGreen)
  ENUM_VALUE(Color, Aqua)
  ENUM_VALUE(Color, Cyan)
  ENUM_VALUE(Color, Tan)
  ENUM_VALUE(Color, DarkBlue)
  ENUM_VALUE(Color, Lavender)
  ENUM_VALUE(Color, Turquoise)
  ENUM_VALUE(Color, DarkGreen)
  ENUM_VALUE(Color, Violet)
  ENUM_VALUE(Color, LightPurple)
  ENUM_VALUE(Color, LimeGreen)
  ENUM_VALUE(Color, Gray)
  ENUM_VALUE(Color, SkyBlue)
  ENUM_VALUE(Color, Yellow)
  ENUM_VALUE(Color, Magenta)
  ENUM_VALUE(Color, LightGreen)
  ENUM_VALUE(Color, Orange)
  ENUM_VALUE(Color, Teal)
  ENUM_VALUE(Color, LightBlue)
  ENUM_VALUE(Color, Red)
  ENUM_VALUE(Color, Brown)
  ENUM_VALUE(Color, Pink)
  ENUM_VALUE(Color, Blue)
  ENUM_VALUE(Color, Green)
  ENUM_VALUE(Color, Purple)
END_ENUM_LIST()

unsigned int
ToColorHex(Color color);

#endif  // CORE_NAMED_COLORS_H
