name: coveralls

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                cxx: [g++-10]
                build_type: [Debug]

        runs-on: ubuntu-20.04

        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Install Dependencies
          run: |
                sudo apt update
                sudo apt install -y libsdl2-dev libassimp-dev clang-9 clang-tidy

        - name: Install python dependencies
          run: |
                pip3 install wheel setuptools gcovr

        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: Configure
          shell: bash
          working-directory: ${{github.workspace}}/build
          env:
                CXX: ${{matrix.cxx}}
          run: cmake -DGENERATE_COVERAGE=ON -DCMAKE_BUILD_TYPE=${{matrix.build_type}} $GITHUB_WORKSPACE

        - name: Build
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: time cmake --build . --config ${{matrix.build_type}}

        - name: Generate coverage files by running test
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: |
                ctest -C ${{matrix.build_type}}
                gcovr -j $(nproc) --delete --root ../ --print-summary --xml-pretty --xml coverage.xml .

        - name: Display coverage
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: |
                cat coverage.xml

        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v2
          with:
            flags: ${{ runner.os }}
            name: ${{ runner.os }}-coverage
            files: ${{github.workspace}}/build/coverage.xml
