name: deploy-online-content

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Install Dependencies
          run: |
                sudo apt update
                sudo apt install -y libsdl2-dev libassimp-dev

        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: Configure
          shell: bash
          working-directory: ${{github.workspace}}/build
          env:
                CXX: clang++-14
          run: cmake -DCMAKE_BUILD_TYPE=Release $GITHUB_WORKSPACE

        - name: Build
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: time cmake --build . --config Release

        - name: Install doxygen
          run: sudo apt install -y doxygen

        - name: Build doxygen
          run: doxygen docs/doxygen.ini
        
        - name: Build demo html files
          working-directory: ${{github.workspace}}/build
          run: |
                ./libs/core/examples-three-dump -w $GITHUB_WORKSPACE/docs/generated
                ./libs/core/examples-palette write-html -w $GITHUB_WORKSPACE/docs/generated
                ./libs/core/examples-coldet -w $GITHUB_WORKSPACE/docs/generated
                ./libs/core/examples-svg-dump -w $GITHUB_WORKSPACE/docs/generated

        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: github.ref == 'refs/heads/master'
          with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                publish_dir: ./docs/generated/
