name: run-cppcheck

on: [push,pull_request]

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Cppcheck install
        run: sudo apt-get install -y cppcheck

      - name: Cppcheck run
        run: |
          cppcheck --enable=all --inconclusive --error-exitcode=0 libs/ apps/ 2> cppcheck-result.txt
          cat cppcheck-result.txt
