name: run-style-checks

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                build_type: [Debug, Release]

        runs-on: ubuntu-22.04

        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Install Dependencies
          run: |
                sudo apt update
                sudo apt install -y libsdl2-dev libassimp-dev

        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: Cache clang-tidy
          id: cache-primes
          uses: actions/cache@v3
          with:
            path: ${{github.workspace}}/build/clang-tidy-store.json
            key: clang-tidy

        - name: Configure
          shell: bash
          working-directory: ${{github.workspace}}/build
          env:
                CXX: clang++-15
          run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} $GITHUB_WORKSPACE

        - name: clang-tidy version
          shell: bash
          working-directory: ${{github.workspace}}
          run: |
                ls /usr/bin/clang-*
                clang-tidy-15 --version
                dotnet run --project ./tools/buildtools/Workbench/ -- path clang-tidy set /usr/bin/clang-tidy-15

        - name: Build
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: time cmake --build . --config ${{matrix.build_type}}

        - name: Run code check (clang-tidy)
          shell: bash
          working-directory: ${{github.workspace}}
          run: dotnet run --project ./tools/buildtools/Workbench/ -- clang tidy libs apps --list

        - name: Run code check (filename check)
          shell: bash
          working-directory: ${{github.workspace}}
          run: dotnet run --project ./tools/buildtools/Workbench/ -- check-file-names libs apps
