name: run-style-checks

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                build_type: [Debug, Release]

        runs-on: ubuntu-20.04

        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Install Dependencies
          run: |
                sudo apt update
                sudo apt install -y libsdl2-dev libassimp-dev clang-9 clang-tidy

        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: Cache clang-tidy
          id: cache-primes
          uses: actions/cache@v3
          with:
            path: ${{github.workspace}}/build/clang-tidy-store.json
            key: clang-tidy

        - name: Configure
          shell: bash
          working-directory: ${{github.workspace}}/build
          env:
                CXX: clang++-12
          run: cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} $GITHUB_WORKSPACE

        - name: clang-tidy version
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: |
                sudo apt-get install -y clang-tidy-12
                ls /usr/bin/clang-*
                alias clang-tidy='/usr/bin/clang-tidy-12'
                which clang-tidy
                clang-tidy-12 --version
                clang-tidy --version

        - name: Build
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: time cmake --build . --config ${{matrix.build_type}}

        - name: Run code check (clang-tidy)
          shell: bash
          working-directory: ${{github.workspace}}
          run: time ./tools/clang.py tidy libs apps --list --tidy clang-tidy-12

        - name: Run code check (filename check)
          shell: bash
          working-directory: ${{github.workspace}}
          run: time ./tools/tools.py check-files libs apps
