name: windows

on: [push, pull_request]

jobs:
    build:
        strategy:
            matrix:
                os: [windows-2016, windows-2019]
                platform: [Win32, x64]
                build_type: [Debug, Release]
                compiler: [vs2019]

        runs-on: ${{matrix.os}}

        steps:
        - uses: actions/checkout@v2
          with:
            submodules: recursive

        - name: Install dependencies
          run: |
                %PYTHON%/python.exe -m pip install requests
                %PYTHON%\python.exe ${{github.workspace}}\tools\windows.py install ${{matrix.compiler}} auto

        - name: Create Build Environment
          run: cmake -E make_directory ${{github.workspace}}/build

        - name: Configure
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: %PYTHON%\python.exe ${{github.workspace}}\tools\windows.py cmake ${{matrix.compiler}} auto

        - name: Build
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: cmake --build . --config ${{matrix.build_type}}

        - name: Test
          shell: bash
          working-directory: ${{github.workspace}}/build
          run: ctest -C ${{matrix.build_type}}
